# -----------------
# LSPatch 与模块设置
# -----------------

# [LSPatch]
LSPatch:
  repo: "JingMatrix/LSPatch"
# 选择使用的 LSPatch 项目（需在 releases 中提供 .jar 文件）
# JingMatrix 维护的 LSPatch 分支已适配 Android 15，若在高版本遇到兼容性问题可考虑使用
# 将官方仓库 "LSPosed/LSPatch" 更改为 "JingMatrix/LSPatch" 即可（使用该分支产生的后果请自负）

# [模块]
modules:
  # --- 预设模块 ---
  # 将值设为 true 来启用模块，设为 false 则禁用
  QAuxiliary: true
  XAutoDaily: false
  TSBattery: true
  QQCleaner: true

  # --- 自定义模块 ---
  custom:
    enable: false # 是否启用自定义模块下载，默认禁用
    list:
    - name: "QStory" # 示例：QStory
      download_link: "https://qstory.sacz.top/update/download"
  # - name: "模块名称"
  #   download_link: "下载链接"
  # 参考上述模板即可添加多个自定义模块（注意对齐空格）
  # 使用自定义模块功能风险自负，本项目作者对于该功能所造成的一切问题概不负责

  # ci_channel: true
  # （待开发，暂不生效）选择是否使用模块的最新CI构建版本（不稳定，不推荐开启）

# -----------------
# QQ 版本设置
# -----------------
QQ:
  custom:
    enable: false # 选择是否修补自定义版本 QQ
    version: "9.1.52" # 自定义QQ版本号（影响最终修补后的文件名）
    url: "https://downv6.qq.com/qqweb/QQ_1/android_apk/Android_9.1.52_64.apk"
    # 自定义 QQ 版本下载链接（确保此链接可直接下载文件）
    # 建议使用 Arm64 安装包，否则需手动更改 Acion Workflow 配置文件中 QAuxiliary 的下载文件名后缀

  latest:
    enable: true # 选择是否修补最新版 QQ
  # 注意：基于最新版 QQ 修补的版本，模块部分功能可能因为未适配而失效，请酌情使用

# -----------------
# 修补设置
# -----------------
force:
  enable: false # 选择是否每次执行时均进行修补，忽略版本更新检查（不推荐长期开启）
